### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by wuaming** [varunjampani/video_prop_networks#1]
Hello, When I cmake your code , there is an error. Could you give some results of drift-chicane to download?

**Comment by varunjampani** [comment]
Hi, 

Can you please let me know the error you get with cmake?

And, if you are interested in visualising the results, you can browse them here: http://davischallenge.org/one_result.html?seq_id=drift-chicane

For quantitative comparisons, can you please send me your email address so that I can share the 'VPN-DeepLab' results with you?

Thanks,
Varun

**Comment by wuaming** [comment]
OK, Thank you very much. my email: feiyingaming@163.com

**Comment by wuaming** [comment]
Thank you very much. my email: feiyingaming@163.com. could you send me your  'VPN-DeepLab' results?




At 2017-04-29 14:30:11, "Varun Jampani" <notifications@github.com> wrote:


Hi,

Can you please let me know the error you get with cmake?

And, if you are interested in visualising the results, you can browse them here: http://davischallenge.org/one_result.html?seq_id=drift-chicane

For quantitative comparisons, can you please send me your email address so that I can share the 'VPN-DeepLab' results with you?

Thanks,
Varun

**Comment by wuaming** [comment]
CMake Error at docs/CMakeLists.txt:82 (file):
  file STRINGS file "/home/wam2/video_prop_networks/lib/caffe/.Doxyfile"
  cannot be read.
This is the error.

**Comment by varunjampani** [comment]
Thanks for the info. I will add '.Doxyfile' to the repo. And, I emailed the VPN-DeepLab results to you.
